# Generated by Django 5.2 on 2025-05-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='twitter_link',
            new_name='x_link',
        ),
    ]
